In [6]:
from rich import print
import numpy as np

np.random.seed(0)
N, n = 3, 3
X = np.random.randn(N, n) * 2
Xc = X - X.mean(0, keepdims=True)
A, B, C = np.linalg.svd(Xc, full_matrices=False)

k = 1
Xp = Xc @ C[:, :k]  # (N, n) @ (n, k) = (N, k)
Xr = Xp[:, :k] @ C[:, :k].T  



for v in Xc:
  print(v)

print("Principle components")
for pc in C:
  print(pc)


print("projected vectors")
for pv in Xp:
  print(pv)


print("Reconstructed vectors")
for rv in Xr:
  print(rv)

[ 0.22474872 -0.61059091  2.02531513]

[ 1.17843042  2.32421065 -1.88671659]

[-1.40317914 -1.71361974 -0.13859854]

Principle components

[-0.37495857 -0.72792074  0.57405355]

[0.53573501 0.33521588 0.77499569]

[-0.7565673   0.59813185  0.26428055]

projected vectors

[-1.94367358]

[2.2307265]

[-0.28705292]

Reconstructed vectors

[ 0.72879706 -1.04129398  1.47051987]

[-0.83643001  1.19507827 -1.68769472]

[ 0.10763295 -0.1537843   0.21717485]

In [105]:
np.random.seed(0)
N, n = 4, 3
X = np.random.randn(N, n) * 2
Xc = X - X.mean(0, keepdims=True)
print(X.mean(0, keepdims=True))
A, B, C = np.linalg.svd(Xc, full_matrices=False)

k = 1
Xp = Xc @ C.T
Xr = Xp[:, :k] @ C[:k, :]

print("C\n", C)
print("Xc\n", Xc)
print("Xp\n", Xp)
print("Xr\n", Xr)

[[2.68281623 1.13020078 0.67625738]]

C
 [[-0.48985437 -0.54681284  0.6789981 ]
 [-0.44063288 -0.51674909 -0.73403885]
 [ 0.75225352 -0.65876103  0.01218808]]

Xc
 [[ 0.84528846 -0.32988636  1.28121859]
 [ 1.79897017  2.6049152  -2.63081314]
 [-0.7826394  -1.4329152  -0.88269508]
 [-1.86161923 -0.84211364  2.23228963]]

Xp
 [[ 0.63626284 -1.14245763  0.8688031 ]
 [-4.09195159 -0.20765392 -0.39479954]
 [ 0.56756748  1.73324677  0.34444708]
 [ 2.88812128 -0.38313521 -0.81845064]]

Xr
 [[-0.31167613 -0.34791669  0.43202125]
 [ 2.00446037  2.23753167 -2.77842734]
 [-0.27802541 -0.31035318  0.38537724]
 [-1.41475883 -1.5792618   1.96102885]]

In [ ]:
k = 2
print(Xp[:, :k])
print(C[:k, :])

[[ 0.63626284 -1.14245763]
 [-4.09195159 -0.20765392]
 [ 0.56756748  1.73324677]
 [ 2.88812128 -0.38313521]]

[[-0.48985437 -0.54681284  0.6789981 ]
 [-0.44063288 -0.51674909 -0.73403885]]

In [128]:
k = 3
for j in range(k):
  for i in range(N):
    # print(Xp[i,:j+1][1] if j+1 == 2 else "arsta")
    pv = [Xp[i, :j+1].item(),0,0] if j+1 == 1 else [Xp[i,:j+1][0].item(), Xp[i,:j+1][1].item(), 0] if j+1 == 2 else Xp[i, :j+1]
    print(pv)

[0.636262836086882, 0, 0]

[-4.0919515880528445, 0, 0]

[0.5675674766587733, 0, 0]

[2.888121275307189, 0, 0]

[0.636262836086882, -1.1424576332514147, 0]

[-4.0919515880528445, -0.20765392287305265, 0]

[0.5675674766587733, 1.7332467694771545, 0]

[2.888121275307189, -0.38313521335268813, 0]

[ 0.63626284 -1.14245763  0.8688031 ]

[-4.09195159 -0.20765392 -0.39479954]

[0.56756748 1.73324677 0.34444708]

[ 2.88812128 -0.38313521 -0.81845064]