In [53]:
from rich import print as pprint
import torch
def showtens(tens):
  pprint(tens.shape)
  pprint(tens)

In [54]:
N = 10 
n = 5  

X = torch.randn(N, n)
X_mean = X.mean(dim=0, keepdim=True) 
X_centered = X - X_mean

showtens(X)
showtens(X_centered)

torch.Size([10, 5])

tensor([[-0.6357,  1.0152,  0.6177, -0.5396,  1.1751],
        [-1.1432, -0.4276, -0.8792, -1.1833,  1.2797],
        [ 1.1314,  0.1996,  2.6056, -0.4328, -0.1873],
        [ 0.3370, -0.1335,  1.4440, -0.4028, -0.4150],
        [-1.6403,  0.1312, -0.9298, -0.3438, -0.3268],
        [ 0.0399, -0.8200, -0.3191,  0.0675,  0.5699],
        [-0.6014,  0.5571, -0.8559, -0.0665, -3.1463],
        [ 0.7959,  0.3085,  1.2051,  0.9296,  0.1070],
        [ 0.9207,  0.6037, -0.0885,  0.1116, -0.2123],
        [ 0.5447,  1.4918, -0.0494, -1.1712,  2.0050]])

torch.Size([10, 5])

tensor([[-0.6106,  0.7226,  0.3426, -0.2364,  1.0902],
        [-1.1181, -0.7202, -1.1542, -0.8802,  1.1948],
        [ 1.1564, -0.0930,  2.3306, -0.1297, -0.2722],
        [ 0.3620, -0.4261,  1.1689, -0.0997, -0.4999],
        [-1.6152, -0.1614, -1.2049, -0.0407, -0.4116],
        [ 0.0650, -1.1126, -0.5941,  0.3707,  0.4850],
        [-0.5763,  0.2645, -1.1309,  0.2366, -3.2312],
        [ 0.8210,  0.0159,  0.9301,  1.2327,  0.0221],
        [ 0.9458,  0.3111, -0.3636,  0.4147, -0.2972],
        [ 0.5697,  1.1992, -0.3245, -0.8681,  1.9201]])

In [55]:
k = 3
W = torch.randn(n, k)
showtens(W)

torch.Size([5, 3])

tensor([[ 0.3314,  0.2192, -0.3886],
        [ 0.7246,  0.0487,  0.5453],
        [-0.0417,  0.2588, -1.2373],
        [-0.6821, -0.5929,  0.0978],
        [-1.8956, -0.0554,  1.1901]])

In [ ]:
XcW = X_centered @ W # (10, 5) @ (5, 3) -> (10, 3)
showtens(XcW)

torch.Size([10, 3])

tensor([[-1.5984,  0.0697,  1.4818],
        [-2.5089, -0.1232,  2.8058],
        [ 0.8233,  0.9441, -3.7205],
        [ 0.7782,  0.4479, -2.4241],
        [ 0.2060, -0.6268,  1.5366],
        [-1.9321, -0.4402,  0.7165],
        [ 6.0116, -0.3674, -2.0548],
        [-0.6379, -0.3106, -1.3143],
        [ 0.8347, -0.1010, -0.0612],
        [-1.9765,  0.5076,  3.0343]])

In [57]:
Xcs = X_centered[0]
Ws = W[:, 0]
pprint(Xcs)
pprint(Ws)
XcsWs = Xcs * Ws
pprint(XcsWs)
pprint(XcsWs.sum())

tensor([-0.6106,  0.7226,  0.3426, -0.2364,  1.0902])

tensor([ 0.3314,  0.7246, -0.0417, -0.6821, -1.8956])

tensor([-0.2024,  0.5236, -0.0143,  0.1613, -2.0667])

tensor(-1.5984)

In [58]:
XcWWT = XcW @ W.T  # (10, 3) @ (3, 5) -> (10, 5)
showtens(XcWWT)

torch.Size([10, 5])

tensor([[ -1.0903,  -0.3468,  -1.7488,   1.1938,   4.7897],
        [ -1.9489,  -0.2940,  -3.3990,   2.0587,   8.1019],
        [  1.9257,  -1.3864,   4.8134,  -1.4851,  -6.0408],
        [  1.2982,  -0.7362,   3.0829,  -1.0335,  -4.3850],
        [ -0.6663,   0.9567,  -2.0720,   0.3814,   1.4730],
        [ -1.0153,  -1.0307,  -0.9200,   1.6489,   4.5396],
        [  2.7104,   3.2178,   2.1970,  -4.0835, -13.8208],
        [  0.2312,  -1.1941,   1.5723,   0.4907,  -0.3377],
        [  0.2783,   0.5665,   0.0149,  -0.5154,  -1.6495],
        [ -1.7229,   0.2472,  -3.5406,   1.3439,   7.3296]])